name: Release and Publish Gem

on:
  workflow_dispatch:

jobs:
  publish:
    uses: epimorphics/github-workflows/.github/workflows/publish-gem.yml@v1
    if: github.ref == 'refs/heads/main'
    secrets:
      packages_token: ${{ secrets.GITHUB_TOKEN }}
