name: Workflow

on:
  push:
    branches-ignore:
      - 'issue/**'
      - 'task/**'
      - 'spike/**'
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore

  workflow_dispatch: {}

jobs:

  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Record desired ruby version"
        id: ruby
        shell: bash
        run: |
          [ -f .ruby-version ] && echo version=$(cat .ruby-version) | tee -a $GITHUB_OUTPUT ||  echo "version=" >> $GITHUB_OUTPUT

      - name: "Setup ruby"
        if:  steps.ruby.outputs.version != ''
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby.outputs.version }}

      - name: Install dependencies (bundle)
        run: bundle install

      - name: Run checks
        run: |
          PAT=${{ secrets.EPI_GPR_READ_ACCESS_TOKEN }} make lint test

  Publish:
    needs: Check
    name: "Build gem package"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Git Information"
      id: gitinfo
      run: |
        echo name=${GITHUB_REF#refs/*/}       | tee -a $GITHUB_OUTPUT
        echo branch=${GITHUB_REF#refs/heads/} | tee -a $GITHUB_OUTPUT
        make tags                             | tee -a $GITHUB_OUTPUT

    - name: "Build gem"
      run: "make gem"

    - name: "Create Release"
      id: release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitinfo.outputs.version }}
        name: v${{ steps.gitinfo.outputs.version }}
        generate_release_notes: true
        draft: false
        prerelease: false
        files: |
          json_rails_logger-${{ steps.gitinfo.outputs.version }}.gem

    - name: "Publish gem"
      run: |
        PAT=${{ secrets.GITHUB_TOKEN }} make publish
